name: dusty-gan
dependencies:
  - ipython
  - matplotlib
  - nvidia::cudatoolkit=11.1
  - pip
  - python=3.8
  - pytorch::pytorch=1.8.1
  - pytorch::torchvision>=0.8.0
  - tqdm
  - pip:
      - black
      - einops
      - hydra_colorlog
      - hydra-core
      - joblib
      - kornia
      - mypy
      - numba
      - omegaconf
      - opencv-python
      - pandas
      - scikit-learn
      - streamlit
      - tensorflow
